### ISSUE TITLE
FilePolicy blocks access to shared documentables

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/DocumentsManager#11]
This is  a **bug | feature request**. (up for interpretation 😅 )

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

`vendor/laravel-enso/filemanager/src/app/Policies/FilePolicy.php` (which from what I can see isn't overruled for Documentables) doesn't take into account the permission-level the user has on a model with documentable trait.

### Steps to Reproduce
1. Upload a document on a Model with Documentable trait
2. log in with a user that has access to that model's _instance_; but is not a supervisor or admin role (use-case: we have multiple supervisor levels & will have shared document sections for all users)

### Expected behavior

being able to open the attached document

### Actual behavior

403 Forbidden

p.s.: sorry if I'm missing something obvious, as I can't imagine there's no way around this by design

**Comment by aocneanu** [comment]
Right now the file policy is stricter, it allows only admins and supervisors to access other users files. The rest of users can only access their file.

But the good thing is that being a policy it can be easily overriden in you local project (a model can only have one policy).

If you have any idea to improve the existing one I'm open to suggestions.

**Comment by jlsjonas** [comment]
🤔 
I'm thinking something along the lines of (still working this out)

```php
        $attachedTo = ($file->attachable->documentable ?: $file->attachable);
        if(method_exists($attachedTo, 'canAccess') && is_callable([$attachedTo, 'canAccess']))
            return $attachedTo->canAccess($user, $file);
        else
            return $user->id === intval($file->created_by);
```
in `FilePolicy`'s `handle`.

This preserves the current default (for simple constructions) but allows overriding the logic per _actual_ model (if you're using Enso _properly_ most files will be attached to a Document, where logic might really defer per documentable)

**Comment by aocneanu** [comment]
looks promising

**Comment by aocneanu** [comment]
Should I close this?

**Comment by jlsjonas** [comment]
Sorry, lost track of this one.
Can I provide a PR for the suggested change?

**Comment by aocneanu** [comment]
Sure.
