### ISSUE TITLE
Problem with UUID in the models

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/DocumentsManager#9]
This is  a **bug or feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
Is there a possibility that UUID can be used in the models? In all my models I use UUID and when I try to use the package in any of these models it gives error in console `prop "id". Expected Number`
And then at the time of saving it gives this other error: `SQLSTATE[01000]: Warning: 1265 Data truncated for column 'documentable_id' at row 1`
Obviously all this happens because the wait as id a number and I send a string of the UUID

![captura de pantalla de 2018-09-13 20-47-39](https://user-images.githubusercontent.com/12703614/45524920-660e7100-b796-11e8-9438-aa387839b08c.png)

**Comment by aocneanu** [comment]
You'll have to make a migration in your project where you change the `documentable_id` column to `varchar`. That's it

**Comment by heyner29** [comment]
Yes, in my project I solve it by changing the migration as you indicate and the props [here](https://github.com/laravel-enso/DocumentsManager/blob/9975425b2e6f19b11c02337cbac9d9ab03c3d384/src/resources/js/components/enso/documents/DocumentsCard.vue#L59) and [here](https://github.com/laravel-enso/DocumentsManager/blob/9975425b2e6f19b11c02337cbac9d9ab03c3d384/src/resources/js/components/enso/documents/Documents.vue#L60) of number to string.

Only that I thought that the changes could be applied to the repository because it does not affect the current operation at all and on the contrary I would add an extra possibility.
Thanks again for such excellent packages.

**Comment by aocneanu** [comment]
Thanks for the kind words.

> it does not affect the current operation at all

This may be true in small projects. Once a project grows the negative perfomance impact becomes significant by using uuid vs id.
